### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by seemsindie** [purcell/less-css-mode#19]
I am noob for emacs, so i don't know exactly what am i doing.
I have this to start the mode for less:

(add-to-list 'auto-mode-alist '("\\.less$" . less-css-mode))

But what i want is less-css-compie after every save, how do i manage to do that? And also with that to now show the output buffer just the message in the status bar

Thanks, Ivan.

**Comment by purcell** [comment]
You can enable that either by putting `(setq less-css-compile-at-save t)` in your startup file, or just use `M-x customize-variable` to customize `less-css-compile-at-save`.

Alternatively, if you want to set it on a file-by-file basis, use [directory local variables](https://www.gnu.org/software/emacs/manual/html_node/elisp/Directory-Local-Variables.html) or [file local variables](https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Local-Variables.html).

Hope that helps!

-Steve
