### ISSUE TITLE
Close or don't show ouput?

### ISSUE THREAD

**Issue by seemsindie** [purcell/less-css-mode#20]
Hello,

I was wondering is there any way to show output in messages, or to now show it at all?

Thanks.

**Comment by purcell** [comment]
Hi - if I understand you correctly, you'd like to be able to enable `less-css-compile-at-save`, but not show the resulting `*compilation*` buffer, and instead see the output in the minibuffer/`*Messages*`?

**Comment by seemsindie** [comment]
Yes, is there option for that?

**Comment by purcell** [comment]
Not yet, but I'm sure I can do it pretty easily.

**Comment by purcell** [comment]
Done in d59a3ff. Thanks.

**Comment by purcell** [comment]
To be clear, the new behaviour is:

- Compilation buffer does not automatically get displayed
- If compilation succeeds, the only message is "Compilation finished"
- If compilation fails, the `*less-css-compilation*` buffer is displayed

This behaviour makes sense to me, and is hopefully what you were looking for. :-)

**Comment by seemsindie** [comment]
Yes that is exactly what i wanted, thanks man :)

**Comment by purcell** [comment]
When you mentioned it, I realised I wanted it too. Then I found that I'd already been working on it...
