### ISSUE TITLE
Configure tab space to 2 instead of 4

### ISSUE THREAD

**Issue by madhavan020985** [purcell/less-css-mode#21]
By default, every tab key puts four spaces in the front. Is there a way, i can customize it to 2 spaces?

I am not seeing any variable for tab space customization inside less-css-mode.el....

**Comment by purcell** [comment]
`less-css-mode` is built on `css-mode`, so customize `css-indent-offset`. If you only want the value to take effect in `less-css-mode`, do something like this (untested):

```el
(add-hook 'less-css-mode-hook (lambda () (set (make-local-variable 'css-indent-offset) 2)))
```
