### ISSUE TITLE
Stable version now longer works with new emacs

### ISSUE THREAD

**Issue by szarsti** [purcell/less-css-mode#23]
I am using stable melpa repo.

When I try to run '(less-css-mode)' I get following error in message console:

```
File mode specification error: (error Wrong css-mode.el: please use the version by Stefan Monnier, bundled with Emacs >= 23.)
if: Wrong css-mode.el: please use the version by Stefan Monnier, bundled with Emacs >= 23.
```

**Comment by purcell** [comment]
What version do you mean by "new emacs"? I can't reproduce this locally, using a current snapshot version.

**Comment by szarsti** [comment]
I am using Emacs 25.1 and less-css-mode v 0.20 from http://stable.melpa.org/packages. 

Version 0.20 seems to be very old. It may be the reason of my issue. Stable melpa is not making packages from github master branch, but from tags. Maybe it would just be enough if you could 'release' more recent, stable version just by tagging it in github.

**Comment by purcell** [comment]
Done - give 0.21 a try when MELPA Stable has built it, and let me know if that helps. (I’m not sure that it will, given the 5 commits added since 0.20.)

**Comment by szarsti** [comment]
It worked! Thank you very much. It must have been a change in one of those 5 commits.

Thank you for great job maintaining this mode.

**Comment by purcell** [comment]
Great, thanks for your help.
