### ISSUE TITLE
Not worked in emacs 25.1.1

### ISSUE THREAD

**Issue by zw963** [purcell/less-css-mode#25]
```cl
Debugger entered--Lisp error: (error "Wrong css-mode.el: please use the version by Stefan Monnier, bundled with Emacs >= 23.")
  signal(error ("Wrong css-mode.el: please use the version by Stefan Monnier, bundled with Emacs >= 23."))
  error("Wrong css-mode.el: please use the version by Stefan Monnier, bundled with Emacs >= 23.")
  (if (boundp (quote css-navigation-syntax-table)) nil (error "Wrong css-mode.el: please use the version by Stefan Monnier, bundled with Emacs >= 23."))
  eval-buffer(#<buffer  *load*> nil "/home/zw963/Dropbox/common/.emacs.d/my-customized-settings/plugins/web/less-css-mode.el" nil t)  ; Reading at buffer position 2804
  load-with-code-conversion("/home/zw963/Dropbox/common/.emacs.d/my-customized-settings/plugins/web/less-css-mode.el" "/home/zw963/Dropbox/common/.emacs.d/my-customized-settings/plugins/web/less-css-mode.el" nil t)
  require(less-css-mode)
  eval((require (quote less-css-mode)) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  #<subr call-interactively>(eval-last-sexp nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> eval-last-sexp nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (eval-last-sexp nil nil))
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by zw963** [comment]
Not worked in emacs 25.2.1 too.

**Comment by purcell** [comment]
I can't reproduce this with either Emacs version, sorry. Probably you have an old incompatible local version of `css-mode.el` on your `load-path`, so Emacs is loading that instead of the version bundled with Emacs. (The error message tells you what to investigate in this case.)

**Comment by zw963** [comment]
>> robably you have an old incompatible local version of css-mode.el on your load-path

No,  no any `css-mode` in my path, and, `emacs 25.1.1` or emacs 24.5.1` bounded css-mode, 
no ``css-navigation-syntax-table`` exists, maybe you local exist a old version css-mode?

**Comment by purcell** [comment]
> No, no any css-mode in my path, and, emacs 25.1.1 or emacs 24.5.1 bounded css-mode,
> no css-navigation-syntax-table keyword exists in el source code

Correct. But recent versions have `css-smie-rules`, and the `less-css-mode` code checks for that too.

> , maybe you local exist a old version css-mode?

Definitely not, sorry.

**Comment by purcell** [comment]
> No, no any css-mode in my path, and, emacs 25.1.1 or emacs 24.5.1 bounded css-mode,
> no css-navigation-syntax-table keyword exists in el source code

Correct. But recent versions have `css-smie-rules`, and the `less-css-mode` code checks for that too -- either is sufficient, so your `css-mode` must have neither.

> , maybe you local exist a old version css-mode?

Definitely not, sorry.

**Comment by zw963** [comment]
@purcell , I make a supid error, sorry, I forget think I pull the newest project, but I not ....

sorry for confuse ...

**Comment by purcell** [comment]
No problem, glad you figured it out.
