### ISSUE TITLE
Should this be removed from Melpa since Emacs has a newer version?

### ISSUE THREAD

**Issue by tarsius** [purcell/less-css-mode#26]
The version of `less-css-mode` that is part of Emacs since 26.1, is never than this version. I think we should remove this from Melpa as users might otherwise "update" to the older version.

**Comment by purcell** [comment]
I thought there was stuff in place in `package.el` that avoided built-in packages ever getting upgraded to MELPA versions?

**Comment by tarsius** [comment]
I don't know, will look into it eventually.

**Comment by tarsius** [comment]
Well, I am just gonna assume there is.
